services:
  # --- Bancos de Dados ---
  usuarios-db:
    image: postgres:13
    container_name: usuarios-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usuarios
    ports:
      - "5432:5432"
    volumes:
      - ./usuarios_db:/var/lib/postgresql/data
      - ./graacc_api_usuarios/src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  #agendamentos-db:
  #  image: postgres:13
  #  container_name: agendamentos-db
  #  environment:
  #    POSTGRES_USER: user
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_DB: agendamentos
  #  ports:
  #    - "5433:5432"
  #  volumes:
  #    - ./agendamentos-db:/var/lib/postgresql/data
  #    - ./graacc_api_agendamentos/src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  #notificacoes-db:
  #  image: postgres:13
  #  container_name: notificacoes-db
  #  environment:
  #    POSTGRES_USER: user
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_DB: notificacoes
  #  ports:
  #    - "5434:5432"
  #  volumes:
  #    - notificacoes-data:/var/lib/postgresql/data

  # --- Mock Server ---
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    command: --port 8080 --verbose
    ports:
      - "9090:8080"
    volumes:
      - ./graacc-api-mock/mappings:/home/wiremock/mappings

  # --- Microsserviços Java ---
  usuarios-api:
    container_name: usuarios-api
    build:
      context: ./graacc_api_usuarios
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://usuarios-db:5432/usuarios
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - SECURITY_TOKEN=secret
      - SECURITY_EMISSOR=codelab
      - URL_API_GRAACC_AGENDAMENTOS=http://agendamentos-api:8080/pacientes
    depends_on:
      - usuarios-db

  agendamentos-api:
    container_name: agendamentos-api
    build:
      context: ./graacc_api_agendamentos
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://usuarios-db:5432/usuarios
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - SECURITY_TOKEN=secret
      - SECURITY_EMISSOR=codelab
    #depends_on:
    #  - agendamentos-db

  notificacoes-api:
    container_name: notificacoes-api
    build:
      context: ./graacc_api_notificacoes
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://usuarios-db:5432/usuarios
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - SECURITY_TOKEN=secret
      - SECURITY_EMISSOR=codelab
    #depends_on:
    #  - notificacoes-db

  orquestrador-api:
    container_name: orquestrador-api
    build:
      context: ./graacc_api_orquestrador
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - URL_MS_USUARIOS=http://usuarios-api:8080
      - URL_MS_AGENDAMENTOS=http://agendamentos-api:8080
      - URL_MS_NOTIFICACOES=http://notificacoes-api:8080
    depends_on:
      - usuarios-api
      - agendamentos-api
      - notificacoes-api

  cors_proxy:
    container_name: cors_proxy
    image: nginx
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/templates

volumes:
  usuarios-data:
  agendamentos-data:
  notificacoes-data:
  usuarios-db:
  agendamentos-db:
  notificacoes-db:
